#!/bin/bash
set -euo pipefail

LIBC_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
LIBC_INCLUDE="$LIBC_ROOT/include"
LIBC_LIB="$LIBC_ROOT/zig-out/lib"
KERNEL_LIBS="$LIBC_ROOT/deps/kernel-libs/genesis-abi/include"
OUT_DIR="$LIBC_ROOT/tests/integration/out"
ZIG_BIN="${ZIG:-zig}"
CLANG_BIN="${CLANG:-clang}"
LD_LLD_BIN="${LD_LLD:-ld.lld}"
AR_BIN="${AR:-ar}"
TEST_SOURCE="${1:-tests/integration/kernel_integration.c}"
TEST_NAME="${2:-trxlibc_integration}"
OUT_ELF="$OUT_DIR/${TEST_NAME}.elf"
OUT_HEADER="$OUT_DIR/hello_trxlibc_elf.h"

mkdir -p "$OUT_DIR"

echo "=== Building trx-libc ==="
cd "$LIBC_ROOT"
"$ZIG_BIN" build

# Zig 0.15.2 can emit an x86_64 archive with an odd-sized member and a
# non-readable member mode when the object layout changes. GNU ar can read
# that archive, so repack the single libc object into a conventional archive
# before invoking lld.
echo "=== Normalizing libc archive ==="
ARCHIVE_STAGE="$(mktemp -d)"
(cd "$ARCHIVE_STAGE" && "$AR_BIN" x "$LIBC_LIB/libc-x86_64.a" && chmod 644 libc.o && "$AR_BIN" rcs libc-fixed.a libc.o)
mv "$ARCHIVE_STAGE/libc-fixed.a" "$LIBC_LIB/libc-x86_64.a"
rm -rf "$ARCHIVE_STAGE"

echo "=== Compiling $TEST_SOURCE ==="
"$CLANG_BIN" -target x86_64-unknown-none \
    -ffreestanding -nostdlib -nostdinc \
    -I"$LIBC_INCLUDE" \
    -I"$KERNEL_LIBS" \
    -c "$TEST_SOURCE" \
    -o "$OUT_DIR/${TEST_NAME}.o"

echo "=== Linking against libc-x86_64.a ==="
"$LD_LLD_BIN" \
    -T tests/integration/userspace.ld \
    -o "$OUT_ELF" \
    "$OUT_DIR/${TEST_NAME}.o" \
    "$LIBC_LIB/libc-x86_64.a" \
    --gc-sections

echo "=== Verifying ELF ==="
file "$OUT_ELF"
size "$OUT_ELF"

echo "=== Generating hex header ==="
RAW_HEADER="$OUT_DIR/.${TEST_NAME}.xxd.h"
xxd -i "$OUT_ELF" > "$RAW_HEADER"
{
    echo "/* Generated by tests/integration/build.sh. */"
    echo "#ifndef HELLO_TRXLIBC_ELF_H"
    echo "#define HELLO_TRXLIBC_ELF_H"
    echo "#include <stddef.h>"
    echo "#include <stdint.h>"
    sed -E \
        -e 's/^unsigned char .*\[\] = \{/static const uint8_t hello_trxlibc_elf[] = {/;' \
        -e 's/^unsigned int .*_len = .*/static const size_t hello_trxlibc_elf_size = sizeof(hello_trxlibc_elf);/' \
        "$RAW_HEADER"
    echo "#endif"
} > "$OUT_HEADER"
rm -f "$RAW_HEADER"

echo "=== Output ==="
ls -la "$OUT_DIR/"
echo
echo "To embed in TerranoxOS kernel:"
echo "  cp $OUT_HEADER /path/to/terranox-os/kernel/core/"
echo "  Then run tests/integration/run-qemu.sh for the full kernel check"
